name: Prerelease

on:
  push:
    branches-ignore:
      - main

jobs:
  prerelease:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    env:
      GITHUB_TOKEN: ${{ secrets.GH_TOKEN_IEVA }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          java-version: '20'
          distribution: 'temurin'
          server-id: github
          server-username: GITHUB_ACTOR
          server-password: GITHUB_TOKEN

      - name: Compute pre-release version
        id: prerelease
        run: |
            BASE=$(mvn -q -DforceStdout -Dexpression=project.version help:evaluate)
            BASE=${BASE%-SNAPSHOT}
            BRANCH=${GITHUB_REF_NAME//\//-}
            UNIQUE=$(date +'%Y%m%d%H%M%S')
            SHA=$(git rev-parse --short HEAD)
            PRERELEASE="${BASE}-${BRANCH}-${UNIQUE}-${SHA}"
            echo "pre_version=$PRERELEASE" >> $GITHUB_OUTPUT
            echo "Computed prerelease version: $PRERELEASE"

      - name: Set pre-release version in pom.xml
        run: |
          mvn -B versions:set -DnewVersion=${{ steps.prerelease.outputs.pre_version }} -DgenerateBackupPoms=false

      - name: Build & deploy prerelease
        run: mvn -B clean deploy -DskipTests
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN_IEVA }}
