name: Prerelease

on:
  push:
    branches-ignore:
      - main

jobs:
  prerelease:
    if: "!contains(github.event.head_commit.message, '[skip prerelease]')"
    runs-on: ubuntu-latest

    permissions:
      contents: write
      packages: write

    env:
      GITHUB_TOKEN: ${{ secrets.GH_TOKEN_IEVA }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.ref_name }}

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          java-version: '20'
          distribution: 'temurin'
          server-id: github
          server-username: GITHUB_ACTOR
          server-password: GITHUB_TOKEN

      - name: Compute pre-release version
        id: prerelease
        run: |
            BASE=$(mvn -q -DforceStdout -Dexpression=project.version help:evaluate)
            BASE=${BASE%-SNAPSHOT}
            BASE=${BASE%%-*}
            BRANCH=${GITHUB_REF_NAME//\//-}
            UNIQUE=${GITHUB_RUN_NUMBER}
            SHA=$(git rev-parse --short HEAD)
            PRERELEASE="${BASE}-${BRANCH}-${UNIQUE}-${SHA}"
            echo "pre_version=$PRERELEASE" >> $GITHUB_OUTPUT
            echo "branch=$BRANCH" >> $GITHUB_OUTPUT
            echo "unique=$UNIQUE" >> $GITHUB_OUTPUT
            echo "sha=$SHA" >> $GITHUB_OUTPUT
            echo "Computed prerelease version: $PRERELEASE"

      - name: Stamp version for this build (we do not commit - messy)
        run: |
          mvn -B versions.set -DnewVersion="${{ steps.prerelease.outputs.pre_version }}" -DgenerateBackupPoms=false
          mvn -B versions:commit

      - name: Build and deploy prerelease
        run: mvn -B clean deploy -DskipTests
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN_IEVA }}

      - name: Tag prerelease (tag matches version in pom)
        run: |
          # TAG="pre-${{ steps.prerelease.outputs.branch }}-${{ steps.prerelease.outputs.unique }}-${{ steps.prerelease.outputs.sha }}"
          TAG="pre-${{ steps.prerelease.outputs.pre_version }}"
          git tag "$TAG"
          git push origin "$TAG"
